version: "3"

services:
  postgres:
    image: postgres
    restart: always
    volumes:
      - ./postgres:/var/lib/postgresql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pguser
      POSTGRES_DB: pgdb
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  web:
    build: ./backend
    environment:
      DATABASE_URL: postgres://pguser:pguser@postgres:5432/pgdb
    depends_on:
      - postgres
    volumes:
      - ./backend:/usr/src/backend
      - /usr/src/app/node_modules
    expose:
      - 8000
    ports:
      - "8000:8000"